const DATOS_PRUEBA = [
  {
    tipo: "Apartamento",
    cant_dormitorios: 2,
    departamento: "Montevideo",
    barrio: "Buceo",
    calle: "Av. Mariscal Francisco Solano Lopez",
    nro_puerta: "1781 bis",
    nro_apartamento: 104,
    venta: true,
    alquiler_anual: true,
    alquiler_temporada: true,
    fotos: "",
    estado: "Pasable",
    dormitorios: 2,
    cocina: "definida",
    baños: 1,
    area_edificada: 50,
    area_tota: 50,
    orientacion: "Oeste",
    anio_construccion: 1975,
    rejas: true,
    cerramiento: true,
    acepta_mascotas: true,
    ambientes: "living comedor, azotea, terraza",
    precio_alquiler: 21000,
    moneda_alquiler: "$",
    precio_venta: 150000,
    moneda_venta: "U$S",
    referencia: "A123-1",
  },
];
